# Generated by Django 5.2.1 on 2025-05-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('l', 'l'), ('m', 'm'), ('dona', 'dona')], default='dona', max_length=10),
        ),
    ]
